AWSTemplateFormatVersion: '2010-09-09'
Resources:

  BatchmateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: batchmate-lambda-glue-bucket-67890
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Function: !GetAtt BatchmateLambda.Arn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: batchmate-lambda-role-2
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: batchmate-lambda-policy-2
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJob
                  - glue:GetJobRun
                Resource: "*"

  BatchmateLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: batchmate-lambda-function-2
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              print("Triggered successfully")
              return {"statusCode": 200}

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BatchmateLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt BatchmateBucket.Arn